name: Publish NuGet Package

# This workflow can only be triggered manually via the "Run workflow" button
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'
      releaseNotes:
        description: 'Release notes'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore NanoGPTNet/NanoGPTNet.csproj

    - name: Build the project
      run: dotnet build NanoGPTNet/NanoGPTNet.csproj --configuration Release --no-restore

    - name: Pack the project
      run: |
        dotnet pack NanoGPTNet/NanoGPTNet.csproj --configuration Release --no-build --output ./nupkg \
          /p:PackageVersion=${{ github.event.inputs.version }} \
          /p:PackageReleaseNotes="${{ github.event.inputs.releaseNotes }}"

    - name: Publish to NuGet
      env:
        NUGET_API: ${{ secrets.NUGET_API }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API --source https://api.nuget.org/v3/index.json
